# Generated by Django 2.2.4 on 2019-09-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosibleEnfermedad',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=200)),
                ('pregunta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('justificacion', models.CharField(max_length=500)),
                ('objetivo', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='SabiasQue',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('demostracion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.CharField(max_length=1)),
                ('diasLimite', models.IntegerField(max_length=700)),
                ('diagnostico', models.CharField(max_length=100)),
            ],
        ),
    ]
